name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install htmlhint globally
        run: npm install -g htmlhint

      - name: Fix permissions for htmlhint
        run: chmod +x $(npm bin)/htmlhint

      - name: Run htmlhint tests
        run: $(npm bin)/htmlhint index.html
